# build 0.0.7
# We are using the iOS build system to create Mac OS X python builds
language: node_js
node_js:
  - "9"

env:
  global:
  - ENCRYPTION_LABEL: "cabb09466128"
  - COMMIT_AUTHOR_EMAIL: "travis@cocomake.co"
  - COMMIT_AUTHOR_NAME: "Travis CI"

cache:
  directories:
    - "cocoblockly/node_modules"
    - "node_modules"

before_install:
  # OS extra info
  - uname -a
  - sudo apt-get -qq update
  - sudo apt-get install -y wine

# Run the tests in both Python 2 and 3
script:
  - bash build-neoblock.sh
  - bash deploy-neoblock.sh

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - "cocoblockly/NeoBlock-darwin-x64.tar.gz"
    - "cocoblockly/NeoBlock-win32-x32.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    