# We are using the iOS build system to create Mac OS X python builds
language: node_js
node_js:
  - stable

env:
  global:
  - ENCRYPTION_LABEL: "cabb09466128"
  - COMMIT_AUTHOR_EMAIL: "travis@cocomake.co"
  - COMMIT_AUTHOR_NAME: "Travis CI"

cache:
  directories:
    - "cocoblockly/node_modules"
    - "node_modules"

before_install:
  # OS extra info
  - uname -a

# Run the tests in both Python 2 and 3
script:
  - bash build-neoblock.sh
  - bash deploy-neoblock.sh