var NeoBlockly = NeoBlockly || {};

NeoBlockly.toolboxStr="";
NeoBlockly.toolboxStr += "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
NeoBlockly.toolboxStr += "<xml id=\"ArduBlocklyToolbox\">";
NeoBlockly.toolboxStr += "   <category id=\"catCocoExamples\" name=\"Examples\">";
NeoBlockly.toolboxStr += "      <category id=\"catCocoTouch\" name=\"Blink led\">";
NeoBlockly.toolboxStr += "         <block type=\"arduino_functions\" id=\"jGvSo#,:^f_1q!cAp!^_\" x=\"38\" y=\"63\">";
NeoBlockly.toolboxStr += "            <statement name=\"SETUP_FUNC\">";
NeoBlockly.toolboxStr += "               <block type=\"variables_set\" id=\"Y!~cJU3a=?G=,Es)*Ijn\">";
NeoBlockly.toolboxStr += "                  <field name=\"VAR\">toggle_led<\/field>";
NeoBlockly.toolboxStr += "                  <value name=\"VALUE\">";
NeoBlockly.toolboxStr += "                     <block type=\"logic_boolean\" id=\"QU;Ks:IwY**S@FE=OwB!\">";
NeoBlockly.toolboxStr += "                        <field name=\"BOOL\">TRUE<\/field>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/value>";
NeoBlockly.toolboxStr += "               <\/block>";
NeoBlockly.toolboxStr += "            <\/statement>";
NeoBlockly.toolboxStr += "            <statement name=\"LOOP_FUNC\">";
NeoBlockly.toolboxStr += "               <block type=\"coco_interval_function\" id=\"r:ECGQ86IKq+FiSe2NO;\">";
NeoBlockly.toolboxStr += "                  <field name=\"TIMER_NAME\">coco_timer_1<\/field>";
NeoBlockly.toolboxStr += "                  <value name=\"TIMER_INTERVAL\">";
NeoBlockly.toolboxStr += "                     <block type=\"math_number\" id=\"sjzURX_#s9EdaCRi=%#3\">";
NeoBlockly.toolboxStr += "                        <field name=\"NUM\">1000<\/field>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/value>";
NeoBlockly.toolboxStr += "                  <statement name=\"DO_BLOCKS\">";
NeoBlockly.toolboxStr += "                     <block type=\"io_digitalwrite\" id=\"dH-pBT`M6@_IS\/d?X3|e\">";
NeoBlockly.toolboxStr += "                        <field name=\"PIN\">PB4<\/field>";
NeoBlockly.toolboxStr += "                        <value name=\"STATE\">";
NeoBlockly.toolboxStr += "                           <block type=\"variables_get\" id=\"q.QhVw^ad%\/Kn\/#YwKN_\">";
NeoBlockly.toolboxStr += "                              <field name=\"VAR\">toggle_led<\/field>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/value>";
NeoBlockly.toolboxStr += "                        <next>";
NeoBlockly.toolboxStr += "                           <block type=\"variables_set\" id=\"]\/]lgm@@vkz}nFEtq|lm\">";
NeoBlockly.toolboxStr += "                              <field name=\"VAR\">toggle_led<\/field>";
NeoBlockly.toolboxStr += "                              <value name=\"VALUE\">";
NeoBlockly.toolboxStr += "                                 <block type=\"logic_negate\" id=\"d|.]5P?^m73aRm8sYLZD\">";
NeoBlockly.toolboxStr += "                                    <value name=\"BOOL\">";
NeoBlockly.toolboxStr += "                                       <block type=\"variables_get\" id=\"P4Du@TFbd-b,n)dgM=jd\">";
NeoBlockly.toolboxStr += "                                          <field name=\"VAR\">toggle_led<\/field>";
NeoBlockly.toolboxStr += "                                       <\/block>";
NeoBlockly.toolboxStr += "                                    <\/value>";
NeoBlockly.toolboxStr += "                                 <\/block>";
NeoBlockly.toolboxStr += "                              <\/value>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/next>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/statement>";
NeoBlockly.toolboxStr += "               <\/block>";
NeoBlockly.toolboxStr += "            <\/statement>";
NeoBlockly.toolboxStr += "         <\/block>";
NeoBlockly.toolboxStr += "      <\/category>";
NeoBlockly.toolboxStr += "      <category id=\"catCocoTouch\" name=\"CocoTouch to Led\">";
NeoBlockly.toolboxStr += "         <block type=\"arduino_functions\" id=\"rPo^`(@DV6rSUp%#6eYs\" x=\"38\" y=\"38\">";
NeoBlockly.toolboxStr += "            <statement name=\"LOOP_FUNC\">";
NeoBlockly.toolboxStr += "               <block type=\"cocotouch_touched\" id=\"g}~M-6KLuJB`,W9qt?KQ\">";
NeoBlockly.toolboxStr += "                  <statement name=\"COCOTOUCH_DOTOUCHED\">";
NeoBlockly.toolboxStr += "                     <block type=\"cocoutil_peakdetect\" id=\"rp|H2=5u6vB,#sVGr40G\">";
NeoBlockly.toolboxStr += "                        <field name=\"COCO_NAME\">peak_detector_1<\/field>";
NeoBlockly.toolboxStr += "                        <value name=\"COCO_VALUE\">";
NeoBlockly.toolboxStr += "                           <block type=\"variables_get\" id=\"TWSfFo`[i7u:-Q~M%{7v\">";
NeoBlockly.toolboxStr += "                              <field name=\"VAR\">velocityValue<\/field>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/value>";
NeoBlockly.toolboxStr += "                        <statement name=\"COCO_DO\">";
NeoBlockly.toolboxStr += "                           <block type=\"controls_if\" id=\"bHGSMJYcj{1t,T5yMwcs\">";
NeoBlockly.toolboxStr += "                              <mutation else=\"1\" \/>";
NeoBlockly.toolboxStr += "                              <value name=\"IF0\">";
NeoBlockly.toolboxStr += "                                 <block type=\"logic_compare\" id=\"X0L9Kfzm_!#a8^bWXyB@\">";
NeoBlockly.toolboxStr += "                                    <field name=\"OP\">GT<\/field>";
NeoBlockly.toolboxStr += "                                    <value name=\"A\">";
NeoBlockly.toolboxStr += "                                       <block type=\"variables_get\" id=\"t!`@Bc;(NsP)]2Lb^ATI\">";
NeoBlockly.toolboxStr += "                                          <field name=\"VAR\">prevVelocity<\/field>";
NeoBlockly.toolboxStr += "                                       <\/block>";
NeoBlockly.toolboxStr += "                                    <\/value>";
NeoBlockly.toolboxStr += "                                    <value name=\"B\">";
NeoBlockly.toolboxStr += "                                       <block type=\"math_number\" id=\"NKGWYlE*^NoWWI5C01fH\">";
NeoBlockly.toolboxStr += "                                          <field name=\"NUM\">520<\/field>";
NeoBlockly.toolboxStr += "                                       <\/block>";
NeoBlockly.toolboxStr += "                                    <\/value>";
NeoBlockly.toolboxStr += "                                 <\/block>";
NeoBlockly.toolboxStr += "                              <\/value>";
NeoBlockly.toolboxStr += "                              <statement name=\"DO0\">";
NeoBlockly.toolboxStr += "                                 <block type=\"io_digitalwrite\" id=\"CHTen!b1?|No3lvZvsG]\">";
NeoBlockly.toolboxStr += "                                    <field name=\"PIN\">PB1<\/field>";
NeoBlockly.toolboxStr += "                                    <value name=\"STATE\">";
NeoBlockly.toolboxStr += "                                       <block type=\"io_highlow\" id=\"rIWPXr0]a(Xd`u,Kpctz\">";
NeoBlockly.toolboxStr += "                                          <field name=\"STATE\">HIGH<\/field>";
NeoBlockly.toolboxStr += "                                       <\/block>";
NeoBlockly.toolboxStr += "                                    <\/value>";
NeoBlockly.toolboxStr += "                                    <next>";
NeoBlockly.toolboxStr += "                                       <block type=\"cocomidi_sendcchires\" id=\"u:sr*?6Q_3_;_%kKsV`7\" disabled=\"true\">";
NeoBlockly.toolboxStr += "                                          <value name=\"COCOMIDI_VALUE\">";
NeoBlockly.toolboxStr += "                                             <block type=\"variables_get\" id=\"bnnbbf^4cgHVV9JT#j+5\">";
NeoBlockly.toolboxStr += "                                                <field name=\"VAR\">prevVelocity<\/field>";
NeoBlockly.toolboxStr += "                                             <\/block>";
NeoBlockly.toolboxStr += "                                          <\/value>";
NeoBlockly.toolboxStr += "                                          <value name=\"COCOMIDI_CHAN\">";
NeoBlockly.toolboxStr += "                                             <block type=\"math_number\" id=\"xCxn@SzM+C!SA~VV,XVw\">";
NeoBlockly.toolboxStr += "                                                <field name=\"NUM\">1<\/field>";
NeoBlockly.toolboxStr += "                                             <\/block>";
NeoBlockly.toolboxStr += "                                          <\/value>";
NeoBlockly.toolboxStr += "                                       <\/block>";
NeoBlockly.toolboxStr += "                                    <\/next>";
NeoBlockly.toolboxStr += "                                 <\/block>";
NeoBlockly.toolboxStr += "                              <\/statement>";
NeoBlockly.toolboxStr += "                              <statement name=\"ELSE\">";
NeoBlockly.toolboxStr += "                                 <block type=\"cocomidi_sendcchires\" id=\",NK5e8npiD!{]Hh.Gy|,\" disabled=\"true\">";
NeoBlockly.toolboxStr += "                                    <value name=\"COCOMIDI_VALUE\">";
NeoBlockly.toolboxStr += "                                       <block type=\"math_number\" id=\"y8a5_g{C~bc##WK!.)j1\">";
NeoBlockly.toolboxStr += "                                          <field name=\"NUM\">0<\/field>";
NeoBlockly.toolboxStr += "                                       <\/block>";
NeoBlockly.toolboxStr += "                                    <\/value>";
NeoBlockly.toolboxStr += "                                    <value name=\"COCOMIDI_CHAN\">";
NeoBlockly.toolboxStr += "                                       <block type=\"math_number\" id=\"5\/o\/\/)a^KW=SwIVGxhJ1\">";
NeoBlockly.toolboxStr += "                                          <field name=\"NUM\">1<\/field>";
NeoBlockly.toolboxStr += "                                       <\/block>";
NeoBlockly.toolboxStr += "                                    <\/value>";
NeoBlockly.toolboxStr += "                                 <\/block>";
NeoBlockly.toolboxStr += "                              <\/statement>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/statement>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/statement>";
NeoBlockly.toolboxStr += "                  <next>";
NeoBlockly.toolboxStr += "                     <block type=\"coco_interval_function\" id=\"RU)C%,4]UWYoZ.I5WQ0_\">";
NeoBlockly.toolboxStr += "                        <field name=\"TIMER_NAME\">default<\/field>";
NeoBlockly.toolboxStr += "                        <value name=\"TIMER_INTERVAL\">";
NeoBlockly.toolboxStr += "                           <block type=\"math_number\" id=\"Ao]7q9mW~,@7TI3^[y5r\">";
NeoBlockly.toolboxStr += "                              <field name=\"NUM\">1000<\/field>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/value>";
NeoBlockly.toolboxStr += "                        <statement name=\"DO_BLOCKS\">";
NeoBlockly.toolboxStr += "                           <block type=\"io_digitalwrite\" id=\"l5`wt~Vp?t.0]cMnxCTS\">";
NeoBlockly.toolboxStr += "                              <field name=\"PIN\">PB1<\/field>";
NeoBlockly.toolboxStr += "                              <value name=\"STATE\">";
NeoBlockly.toolboxStr += "                                 <block type=\"io_highlow\" id=\"e|Rk6-(b6f2_tz`q:l^?\">";
NeoBlockly.toolboxStr += "                                    <field name=\"STATE\">LOW<\/field>";
NeoBlockly.toolboxStr += "                                 <\/block>";
NeoBlockly.toolboxStr += "                              <\/value>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/statement>";
NeoBlockly.toolboxStr += "                        <next>";
NeoBlockly.toolboxStr += "                           <block type=\"cocomidi_update\" id=\":w?.oZcQNUU3+Q%C%f=^\" disabled=\"true\" \/>";
NeoBlockly.toolboxStr += "                        <\/next>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/next>";
NeoBlockly.toolboxStr += "               <\/block>";
NeoBlockly.toolboxStr += "            <\/statement>";
NeoBlockly.toolboxStr += "         <\/block>";
NeoBlockly.toolboxStr += "      <\/category>";
NeoBlockly.toolboxStr += "      <category id=\"catCocoTouch\" name=\"CocoTouch to Midi\">";
NeoBlockly.toolboxStr += "         <block type=\"arduino_functions\" id=\"jt2UYe\/a:4opih^:VQ`^\" x=\"37\" y=\"38\">";
NeoBlockly.toolboxStr += "            <statement name=\"LOOP_FUNC\">";
NeoBlockly.toolboxStr += "               <block type=\"cocotouch_touched\" id=\"le|kxys6yaW20{S|+eXd\">";
NeoBlockly.toolboxStr += "                  <statement name=\"COCOTOUCH_DOTOUCHED\">";
NeoBlockly.toolboxStr += "                     <block type=\"cocomidi_sendcchires\" id=\"g_(mUH|XSPN*et\/tmi_M\">";
NeoBlockly.toolboxStr += "                        <value name=\"COCOMIDI_VALUE\">";
NeoBlockly.toolboxStr += "                           <block type=\"variables_get\" id=\"]y8:aJT_sqB}[0.oBL7.\">";
NeoBlockly.toolboxStr += "                              <field name=\"VAR\">filtered_value<\/field>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/value>";
NeoBlockly.toolboxStr += "                        <value name=\"COCOMIDI_CHAN\">";
NeoBlockly.toolboxStr += "                           <block type=\"math_number\" id=\"g(|%*{Au|EA*BcTk[w8S\">";
NeoBlockly.toolboxStr += "                              <field name=\"NUM\">1<\/field>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/value>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/statement>";
NeoBlockly.toolboxStr += "                  <next>";
NeoBlockly.toolboxStr += "                     <block type=\"cocomidi_update\" id=\"6jAg-g-R-821#79iBZX`\" \/>";
NeoBlockly.toolboxStr += "                  <\/next>";
NeoBlockly.toolboxStr += "               <\/block>";
NeoBlockly.toolboxStr += "            <\/statement>";
NeoBlockly.toolboxStr += "         <\/block>";
NeoBlockly.toolboxStr += "      <\/category>";
NeoBlockly.toolboxStr += "      <category id=\"catCocoMidi\" name=\"CocoMidi\">";
NeoBlockly.toolboxStr += "         <block type=\"arduino_functions\" id=\"Gfs=i-2ol,.H[PFJytg(\" x=\"63\" y=\"88\">";
NeoBlockly.toolboxStr += "            <statement name=\"LOOP_FUNC\">";
NeoBlockly.toolboxStr += "               <block type=\"cocomidi_sendnote_var\" id=\"SZV=[c-09L;lgu-cC[80\">";
NeoBlockly.toolboxStr += "                  <value name=\"COCOMIDI_STATE\">";
NeoBlockly.toolboxStr += "                     <block type=\"cocomidi_note_state\" id=\"6t}AyCckvHfyBJMQ[ps]\">";
NeoBlockly.toolboxStr += "                        <field name=\"MIDI_NOTE_STATE\">MIDI_NOTEON<\/field>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/value>";
NeoBlockly.toolboxStr += "                  <value name=\"COCOMIDI_CHAN\">";
NeoBlockly.toolboxStr += "                     <block type=\"math_number\" id=\"(lY+A#b}:9?v@oBmied%\">";
NeoBlockly.toolboxStr += "                        <field name=\"NUM\">22<\/field>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/value>";
NeoBlockly.toolboxStr += "                  <value name=\"COCOMIDI_VEL\">";
NeoBlockly.toolboxStr += "                     <block type=\"math_number\" id=\"m2?u-m:pR+U*[DwmjnWj\">";
NeoBlockly.toolboxStr += "                        <field name=\"NUM\">127<\/field>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/value>";
NeoBlockly.toolboxStr += "                  <next>";
NeoBlockly.toolboxStr += "                     <block type=\"cocomidi_delay\" id=\"RQ[U*2U`nuOtn%pam3YI\">";
NeoBlockly.toolboxStr += "                        <value name=\"COCOMIDI_DELAY\">";
NeoBlockly.toolboxStr += "                           <block type=\"math_number\" id=\"eSzr;WN5_[7@r0NC:KX=\">";
NeoBlockly.toolboxStr += "                              <field name=\"NUM\">500<\/field>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/value>";
NeoBlockly.toolboxStr += "                        <next>";
NeoBlockly.toolboxStr += "                           <block type=\"cocomidi_sendnote_var\" id=\"UvQ0RrSBXTYq@_\/^jy7w\">";
NeoBlockly.toolboxStr += "                              <value name=\"COCOMIDI_STATE\">";
NeoBlockly.toolboxStr += "                                 <block type=\"cocomidi_note_state\" id=\"w|pPWlU2{F*#yk36=]HU\">";
NeoBlockly.toolboxStr += "                                    <field name=\"MIDI_NOTE_STATE\">MIDI_NOTEON<\/field>";
NeoBlockly.toolboxStr += "                                 <\/block>";
NeoBlockly.toolboxStr += "                              <\/value>";
NeoBlockly.toolboxStr += "                              <value name=\"COCOMIDI_CHAN\">";
NeoBlockly.toolboxStr += "                                 <block type=\"math_number\" id=\"]U=BoPM|4M@H0xRru9=l\">";
NeoBlockly.toolboxStr += "                                    <field name=\"NUM\">22<\/field>";
NeoBlockly.toolboxStr += "                                 <\/block>";
NeoBlockly.toolboxStr += "                              <\/value>";
NeoBlockly.toolboxStr += "                              <value name=\"COCOMIDI_VEL\">";
NeoBlockly.toolboxStr += "                                 <block type=\"math_number\" id=\"4XPw~(I-5AX_[gAP[RDl\">";
NeoBlockly.toolboxStr += "                                    <field name=\"NUM\">127<\/field>";
NeoBlockly.toolboxStr += "                                 <\/block>";
NeoBlockly.toolboxStr += "                              <\/value>";
NeoBlockly.toolboxStr += "                              <next>";
NeoBlockly.toolboxStr += "                                 <block type=\"cocomidi_delay\" id=\"6Gy8(ln!)232WCTbtczw\">";
NeoBlockly.toolboxStr += "                                    <value name=\"COCOMIDI_DELAY\">";
NeoBlockly.toolboxStr += "                                       <block type=\"math_number\" id=\"9QQMKwX.es;R|a1KkB8C\">";
NeoBlockly.toolboxStr += "                                          <field name=\"NUM\">500<\/field>";
NeoBlockly.toolboxStr += "                                       <\/block>";
NeoBlockly.toolboxStr += "                                    <\/value>";
NeoBlockly.toolboxStr += "                                 <\/block>";
NeoBlockly.toolboxStr += "                              <\/next>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/next>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/next>";
NeoBlockly.toolboxStr += "               <\/block>";
NeoBlockly.toolboxStr += "            <\/statement>";
NeoBlockly.toolboxStr += "         <\/block>";
NeoBlockly.toolboxStr += "      <\/category>";
NeoBlockly.toolboxStr += "      <category id=\"catCocoMidi\" name=\"Potentio to CocoMidi\">";
NeoBlockly.toolboxStr += "         <block type=\"arduino_functions\" id=\"5Z;sl%)oCHl3Cn=6q%,,\" x=\"9\" y=\"3\">";
NeoBlockly.toolboxStr += "            <statement name=\"LOOP_FUNC\">";
NeoBlockly.toolboxStr += "               <block type=\"cocomidi_sendcchires\" id=\"I6,Pt_hsL)D@Zu46p_^[\">";
NeoBlockly.toolboxStr += "                  <value name=\"COCOMIDI_VALUE\">";
NeoBlockly.toolboxStr += "                     <block type=\"io_analogread\" id=\"[a7Rtx\/3pW)ceu%?7lK~\">";
NeoBlockly.toolboxStr += "                        <field name=\"PIN\">A1<\/field>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/value>";
NeoBlockly.toolboxStr += "                  <value name=\"COCOMIDI_CHAN\">";
NeoBlockly.toolboxStr += "                     <block type=\"math_number\" id=\"7xxz3iUe8;BDZvI\/5H]2\">";
NeoBlockly.toolboxStr += "                        <field name=\"NUM\">1<\/field>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/value>";
NeoBlockly.toolboxStr += "                  <next>";
NeoBlockly.toolboxStr += "                     <block type=\"cocomidi_delay\" id=\"O8M`2V:a5-L81PVvhW@\/\">";
NeoBlockly.toolboxStr += "                        <value name=\"COCOMIDI_DELAY\">";
NeoBlockly.toolboxStr += "                           <block type=\"math_number\" id=\"pK9nwuf\/Sz_8YQ3FlP*p\">";
NeoBlockly.toolboxStr += "                              <field name=\"NUM\">5<\/field>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/value>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/next>";
NeoBlockly.toolboxStr += "               <\/block>";
NeoBlockly.toolboxStr += "            <\/statement>";
NeoBlockly.toolboxStr += "         <\/block>";
NeoBlockly.toolboxStr += "      <\/category>";
NeoBlockly.toolboxStr += "      <category id=\"catCocoSynth\" name=\"CocoSynth\">";
NeoBlockly.toolboxStr += "         <block type=\"arduino_functions\" id=\"^}@SOl,N#YB49.qgQN]M\" x=\"38\" y=\"38\">";
NeoBlockly.toolboxStr += "            <statement name=\"SETUP_FUNC\">";
NeoBlockly.toolboxStr += "               <block type=\"coco_synth_setupvoice\" id=\"jP,[^(j_i6y1\/vP,x1|8\" inline=\"false\">";
NeoBlockly.toolboxStr += "                  <field name=\"COCO_VOICE\">0<\/field>";
NeoBlockly.toolboxStr += "                  <field name=\"COCO_WAVEFORM\">SINE<\/field>";
NeoBlockly.toolboxStr += "                  <field name=\"COCO_ENVELOPE\">ENVELOPE0<\/field>";
NeoBlockly.toolboxStr += "                  <field name=\"COCO_PITCH\">77<\/field>";
NeoBlockly.toolboxStr += "                  <field name=\"COCO_LENGTH\">60<\/field>";
NeoBlockly.toolboxStr += "                  <field name=\"COCO_MOD\">64<\/field>";
NeoBlockly.toolboxStr += "                  <comment pinned=\"true\" h=\"80\" w=\"160\">Connect your speaker to pin 5";
NeoBlockly.toolboxStr += "Sine wave instrument<\/comment>";
NeoBlockly.toolboxStr += "                  <next>";
NeoBlockly.toolboxStr += "                     <block type=\"coco_synth_setupvoice\" id=\"^pTol#6@O}6=7MR%rEk`\" inline=\"false\" collapsed=\"true\">";
NeoBlockly.toolboxStr += "                        <field name=\"COCO_VOICE\">1<\/field>";
NeoBlockly.toolboxStr += "                        <field name=\"COCO_WAVEFORM\">NOISE<\/field>";
NeoBlockly.toolboxStr += "                        <field name=\"COCO_ENVELOPE\">ENVELOPE0<\/field>";
NeoBlockly.toolboxStr += "                        <field name=\"COCO_PITCH\">50<\/field>";
NeoBlockly.toolboxStr += "                        <field name=\"COCO_LENGTH\">100<\/field>";
NeoBlockly.toolboxStr += "                        <field name=\"COCO_MOD\">32<\/field>";
NeoBlockly.toolboxStr += "                        <comment pinned=\"false\" h=\"80\" w=\"160\">Noise Instrument setup<\/comment>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/next>";
NeoBlockly.toolboxStr += "               <\/block>";
NeoBlockly.toolboxStr += "            <\/statement>";
NeoBlockly.toolboxStr += "            <statement name=\"LOOP_FUNC\">";
NeoBlockly.toolboxStr += "               <block type=\"cocosynth_interval_function\" id=\"~B8r^bj{E;NjR;M~,}8[\">";
NeoBlockly.toolboxStr += "                  <field name=\"TIMER_NAME\">synth_timer_1<\/field>";
NeoBlockly.toolboxStr += "                  <comment pinned=\"true\" h=\"80\" w=\"160\">every 1 sec trigger metronome<\/comment>";
NeoBlockly.toolboxStr += "                  <value name=\"TIMER_INTERVAL\">";
NeoBlockly.toolboxStr += "                     <block type=\"math_number\" id=\"!!xw1WI#qCYFd*DDt,v9\">";
NeoBlockly.toolboxStr += "                        <field name=\"NUM\">1000<\/field>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/value>";
NeoBlockly.toolboxStr += "                  <statement name=\"DO_BLOCKS\">";
NeoBlockly.toolboxStr += "                     <block type=\"coco_synth_trigger\" id=\"k#**O~xu3VaEGMV6q8vc\">";
NeoBlockly.toolboxStr += "                        <value name=\"NAME\">";
NeoBlockly.toolboxStr += "                           <block type=\"math_number\" id=\"TM=3w+Rs:.2tTeaIrH!q\">";
NeoBlockly.toolboxStr += "                              <field name=\"NUM\">0<\/field>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/value>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/statement>";
NeoBlockly.toolboxStr += "                  <next>";
NeoBlockly.toolboxStr += "                     <block type=\"cocosynth_interval_function\" id=\"wce5](b4h6H:U4}MwHwL\">";
NeoBlockly.toolboxStr += "                        <field name=\"TIMER_NAME\">synth_timer_2<\/field>";
NeoBlockly.toolboxStr += "                        <comment pinned=\"false\" h=\"80\" w=\"160\">every 2 sec trigger noise instrument<\/comment>";
NeoBlockly.toolboxStr += "                        <value name=\"TIMER_INTERVAL\">";
NeoBlockly.toolboxStr += "                           <block type=\"math_number\" id=\"yA;mqzu%REf[`Dna]wR,\">";
NeoBlockly.toolboxStr += "                              <field name=\"NUM\">2000<\/field>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/value>";
NeoBlockly.toolboxStr += "                        <statement name=\"DO_BLOCKS\">";
NeoBlockly.toolboxStr += "                           <block type=\"coco_synth_miditrigger\" id=\"M`VMwwM4u?-[UOvcm:W[\">";
NeoBlockly.toolboxStr += "                              <value name=\"NAME\">";
NeoBlockly.toolboxStr += "                                 <block type=\"math_number\" id=\"I~kA!gArS8.44rAa=A!G\">";
NeoBlockly.toolboxStr += "                                    <field name=\"NUM\">1<\/field>";
NeoBlockly.toolboxStr += "                                 <\/block>";
NeoBlockly.toolboxStr += "                              <\/value>";
NeoBlockly.toolboxStr += "                              <value name=\"NOTE\">";
NeoBlockly.toolboxStr += "                                 <block type=\"math_random_int\" id=\"U46gXu#9Iome+Y(VM,Ct\">";
NeoBlockly.toolboxStr += "                                    <value name=\"FROM\">";
NeoBlockly.toolboxStr += "                                       <block type=\"math_number\" id=\"_QV*zM@aq-0U}u14)gdX\">";
NeoBlockly.toolboxStr += "                                          <field name=\"NUM\">1<\/field>";
NeoBlockly.toolboxStr += "                                       <\/block>";
NeoBlockly.toolboxStr += "                                    <\/value>";
NeoBlockly.toolboxStr += "                                    <value name=\"TO\">";
NeoBlockly.toolboxStr += "                                       <block type=\"math_number\" id=\"j8AdqP7W~_d.2{:o%;x2\">";
NeoBlockly.toolboxStr += "                                          <field name=\"NUM\">100<\/field>";
NeoBlockly.toolboxStr += "                                       <\/block>";
NeoBlockly.toolboxStr += "                                    <\/value>";
NeoBlockly.toolboxStr += "                                 <\/block>";
NeoBlockly.toolboxStr += "                              <\/value>";
NeoBlockly.toolboxStr += "                           <\/block>";
NeoBlockly.toolboxStr += "                        <\/statement>";
NeoBlockly.toolboxStr += "                     <\/block>";
NeoBlockly.toolboxStr += "                  <\/next>";
NeoBlockly.toolboxStr += "               <\/block>";
NeoBlockly.toolboxStr += "            <\/statement>";
NeoBlockly.toolboxStr += "         <\/block>";
NeoBlockly.toolboxStr += "      <\/category>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catLogic\" name=\"Logic\">";
NeoBlockly.toolboxStr += "      <block type=\"controls_if\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"logic_compare\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"logic_operation\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"logic_negate\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"logic_boolean\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"logic_null\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"logic_ternary\" \/>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catLoops\" name=\"Loops\">";
NeoBlockly.toolboxStr += "      <block type=\"controls_repeat_ext\">";
NeoBlockly.toolboxStr += "         <value name=\"TIMES\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">10<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"controls_whileUntil\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"controls_for\">";
NeoBlockly.toolboxStr += "         <value name=\"FROM\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">1<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "         <value name=\"TO\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">10<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "         <value name=\"BY\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">1<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"controls_flow_statements\" \/>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catMath\" name=\"Math\">";
NeoBlockly.toolboxStr += "      <block type=\"math_number\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"math_arithmetic\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"math_single\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"math_trig\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"math_constant\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"math_number_property\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"math_change\">";
NeoBlockly.toolboxStr += "         <value name=\"DELTA\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">1<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"math_round\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"math_modulo\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"math_constrain\">";
NeoBlockly.toolboxStr += "         <value name=\"LOW\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">1<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "         <value name=\"HIGH\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">100<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"math_random_int\">";
NeoBlockly.toolboxStr += "         <value name=\"FROM\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">1<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "         <value name=\"TO\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">100<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"math_random_float\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"base_map\" \/>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catText\" name=\"Text\">";
NeoBlockly.toolboxStr += "      <block type=\"text\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"cocomake_singlechar\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"text_join\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"text_append\">";
NeoBlockly.toolboxStr += "         <value name=\"TEXT\">";
NeoBlockly.toolboxStr += "            <block type=\"text\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"text_length\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"text_isEmpty\" \/>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catVariables\" name=\"Variables\">";
NeoBlockly.toolboxStr += "      <block type=\"variables_get\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"variables_set\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"variables_set\">";
NeoBlockly.toolboxStr += "         <value name=\"VALUE\">";
NeoBlockly.toolboxStr += "            <block type=\"variables_set_type\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"variables_set_type\" \/>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catFunctions\" name=\"Functions\" custom=\"PROCEDURE\" \/>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catInputOutput\" name=\"Input\/Output\">";
NeoBlockly.toolboxStr += "      <block type=\"variables_set\">";
NeoBlockly.toolboxStr += "         <value name=\"VALUE\">";
NeoBlockly.toolboxStr += "            <block type=\"io_analogread\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"variables_set\">";
NeoBlockly.toolboxStr += "         <value name=\"VALUE\">";
NeoBlockly.toolboxStr += "            <block type=\"io_digitalread\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"io_digitalwrite\">";
NeoBlockly.toolboxStr += "         <value name=\"STATE\">";
NeoBlockly.toolboxStr += "            <block type=\"io_highlow\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"io_digitalread\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"coco_readpullup\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"io_builtin_led\">";
NeoBlockly.toolboxStr += "         <value name=\"STATE\">";
NeoBlockly.toolboxStr += "            <block type=\"io_highlow\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"io_analogwrite\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"io_analogread\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"io_highlow\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"io_pulsein\">";
NeoBlockly.toolboxStr += "         <value name=\"PULSETYPE\">";
NeoBlockly.toolboxStr += "            <shadow type=\"io_highlow\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"io_pulsetimeout\">";
NeoBlockly.toolboxStr += "         <value name=\"PULSETYPE\">";
NeoBlockly.toolboxStr += "            <shadow type=\"io_highlow\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "         <value name=\"TIMEOUT\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catTime\" name=\"Time\">";
NeoBlockly.toolboxStr += "      <block type=\"time_delay\">";
NeoBlockly.toolboxStr += "         <value name=\"DELAY_TIME_MILI\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">1000<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"coco_interval_function\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"time_delaymicros\">";
NeoBlockly.toolboxStr += "         <value name=\"DELAY_TIME_MICRO\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">100<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"time_millis\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"time_micros\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"coco_delayms\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"coco_delayus\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"coco_delayms\" id=\"n8!w)48dfFK;8MobuzE:\" x=\"112\" y=\"362\">";
NeoBlockly.toolboxStr += "         <value name=\"COCOMIDI_DELAY\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\" id=\"8Xx.],i5o:Iaqx+tc@!W\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">100<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"infinite_loop\" \/>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catAudio\" name=\"Audio\">";
NeoBlockly.toolboxStr += "      <block type=\"io_tone\">";
NeoBlockly.toolboxStr += "         <field name=\"TONEPIN\">0<\/field>";
NeoBlockly.toolboxStr += "         <value name=\"FREQUENCY\">";
NeoBlockly.toolboxStr += "            <shadow type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">220<\/field>";
NeoBlockly.toolboxStr += "            <\/shadow>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"io_notone\" \/>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catMotors\" name=\"Motors\">";
NeoBlockly.toolboxStr += "      <block type=\"servo_write\">";
NeoBlockly.toolboxStr += "         <value name=\"SERVO_ANGLE\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">90<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"servo_read\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"stepper_config\">";
NeoBlockly.toolboxStr += "         <field name=\"STEPPER_PIN1\">1<\/field>";
NeoBlockly.toolboxStr += "         <field name=\"STEPPER_PIN2\">2<\/field>";
NeoBlockly.toolboxStr += "         <value name=\"STEPPER_STEPS\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">100<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "         <value name=\"STEPPER_SPEED\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">10<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"stepper_step\">";
NeoBlockly.toolboxStr += "         <value name=\"STEPPER_STEPS\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">10<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catComms\" name=\"Comms\">";
NeoBlockly.toolboxStr += "      <block type=\"serial_setup\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"serial_print\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"text_prompt_ext\">";
NeoBlockly.toolboxStr += "         <value name=\"TEXT\">";
NeoBlockly.toolboxStr += "            <block type=\"text\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"spi_setup\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"spi_transfer\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"spi_transfer_return\" \/>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catCocoKey\" name=\"CocoKeyboard\">";
NeoBlockly.toolboxStr += "      <block type=\"cocokey_sendkeystroke\">";
NeoBlockly.toolboxStr += "         <value name=\"COCOKEY_STROKE\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">0<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"cocokey_sendkeystroke\">";
NeoBlockly.toolboxStr += "         <value name=\"COCOKEY_STROKE\">";
NeoBlockly.toolboxStr += "            <block type=\"cocomake_singlechar\">";
NeoBlockly.toolboxStr += "               <field name=\"TEXT\">C<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"cocokey_delay\">";
NeoBlockly.toolboxStr += "         <value name=\"COCOKEY_DELAY\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">500<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"cocokey_print\">";
NeoBlockly.toolboxStr += "         <value name=\"COCOKEY_PRINT\">";
NeoBlockly.toolboxStr += "            <block type=\"text\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"cocokey_update\" \/>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catCocoMidi\" name=\"CocoMidi\">";
NeoBlockly.toolboxStr += "      <block type=\"cocomidi_sendnote_var\">";
NeoBlockly.toolboxStr += "         <value name=\"COCOMIDI_STATE\">";
NeoBlockly.toolboxStr += "            <block type=\"cocomidi_note_state\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "         <value name=\"COCOMIDI_CHAN\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">0<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "         <value name=\"COCOMIDI_VEL\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">0<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"cocomidi_sendcchires\">";
NeoBlockly.toolboxStr += "         <value name=\"COCOMIDI_VALUE\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">0<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "         <value name=\"COCOMIDI_CHAN\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">1<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"cocomidi_sendcchires\">";
NeoBlockly.toolboxStr += "         <value name=\"COCOMIDI_VALUE\">";
NeoBlockly.toolboxStr += "            <block type=\"variables_get\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "         <value name=\"COCOMIDI_CHAN\">";
NeoBlockly.toolboxStr += "            <block type=\"variables_get\" \/>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"cocomidi_update\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"cocomidi_note_state\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"cocomidi_message\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"cocomidi_read\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"cocomidi_delay\">";
NeoBlockly.toolboxStr += "         <value name=\"COCOMIDI_DELAY\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">500<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catCocoMouse\" name=\"CocoMouse\">";
NeoBlockly.toolboxStr += "      <block type=\"cocokey_update\" \/>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catCocoTouch\" name=\"CocoTouch\">";
NeoBlockly.toolboxStr += "      <block type=\"cocotouch_touched\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"variables_get\">";
NeoBlockly.toolboxStr += "         <field name=\"VAR\">velocityValue<\/field>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"variables_get\">";
NeoBlockly.toolboxStr += "         <field name=\"VAR\">prevVelocity<\/field>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"variables_get\">";
NeoBlockly.toolboxStr += "         <field name=\"VAR\">filtered_value<\/field>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catCocoSynth\" name=\"CocoSynth\">";
NeoBlockly.toolboxStr += "      <block type=\"coco_synth_setupvoice\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"coco_synth_delay\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"cocosynth_interval_function\" id=\"l#cYCg3[Xafg#bmHLYz6\" x=\"162\" y=\"488\">";
NeoBlockly.toolboxStr += "         <field name=\"TIMER_NAME\">synth_timer_1<\/field>";
NeoBlockly.toolboxStr += "         <value name=\"TIMER_INTERVAL\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\" id=\";=T})9b-GmWh.s+xKPpt\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">1000<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "      <block type=\"coco_synth_setmod\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"coco_synth_setmod_field\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"coco_synth_trigger\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"coco_synth_miditrigger\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"coco_synth_voice\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"coco_synth_setwave_field\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"coco_synth_setenvelope_field\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"coco_synth_setpitch\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"coco_synth_setlength\" \/>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "   <sep \/>";
NeoBlockly.toolboxStr += "   <category id=\"catCocoUtil\" name=\"CocoUtil\">";
NeoBlockly.toolboxStr += "      <block type=\"cocoutil_peakdetect\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"cocoutil_getvelocity\" \/>";
NeoBlockly.toolboxStr += "      <block type=\"cocoutil_getmova\" id=\"2aiF`je~9wv+%8u+HhEh\" x=\"163\" y=\"188\">";
NeoBlockly.toolboxStr += "         <field name=\"COCO_NAME\">coco_mova_1<\/field>";
NeoBlockly.toolboxStr += "         <value name=\"COCO_MA\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\" id=\"tR6T(Mzr*EsVe\/*(f_uM\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">0.2<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "         <value name=\"COCO_VALUE\">";
NeoBlockly.toolboxStr += "            <block type=\"math_number\" id=\"Xmi6=.7+8I(y_|V3*pIS\">";
NeoBlockly.toolboxStr += "               <field name=\"NUM\">0<\/field>";
NeoBlockly.toolboxStr += "            <\/block>";
NeoBlockly.toolboxStr += "         <\/value>";
NeoBlockly.toolboxStr += "      <\/block>";
NeoBlockly.toolboxStr += "   <\/category>";
NeoBlockly.toolboxStr += "<\/xml>";
