var CocoBlockly = CocoBlockly || {};

CocoBlockly.toolboxStr="";
CocoBlockly.toolboxStr += "<?xml version=\"1.0\" encoding=\"UTF-8\"?>";
CocoBlockly.toolboxStr += "<xml id=\"ArduBlocklyToolbox\">";
CocoBlockly.toolboxStr += "   <category id=\"catCocoExamples\" name=\"Examples\">";
CocoBlockly.toolboxStr += "      <category id=\"catCocoTouch\" name=\"Blink led\">";
CocoBlockly.toolboxStr += "         <block type=\"arduino_functions\" id=\"jGvSo#,:^f_1q!cAp!^_\" x=\"38\" y=\"63\">";
CocoBlockly.toolboxStr += "            <statement name=\"SETUP_FUNC\">";
CocoBlockly.toolboxStr += "               <block type=\"variables_set\" id=\"Y!~cJU3a=?G=,Es)*Ijn\">";
CocoBlockly.toolboxStr += "                  <field name=\"VAR\">toggle_led<\/field>";
CocoBlockly.toolboxStr += "                  <value name=\"VALUE\">";
CocoBlockly.toolboxStr += "                     <block type=\"logic_boolean\" id=\"QU;Ks:IwY**S@FE=OwB!\">";
CocoBlockly.toolboxStr += "                        <field name=\"BOOL\">TRUE<\/field>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/value>";
CocoBlockly.toolboxStr += "               <\/block>";
CocoBlockly.toolboxStr += "            <\/statement>";
CocoBlockly.toolboxStr += "            <statement name=\"LOOP_FUNC\">";
CocoBlockly.toolboxStr += "               <block type=\"coco_interval_function\" id=\"r:ECGQ86IKq+FiSe2NO;\">";
CocoBlockly.toolboxStr += "                  <field name=\"TIMER_NAME\">coco_timer_1<\/field>";
CocoBlockly.toolboxStr += "                  <value name=\"TIMER_INTERVAL\">";
CocoBlockly.toolboxStr += "                     <block type=\"math_number\" id=\"sjzURX_#s9EdaCRi=%#3\">";
CocoBlockly.toolboxStr += "                        <field name=\"NUM\">1000<\/field>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/value>";
CocoBlockly.toolboxStr += "                  <statement name=\"DO_BLOCKS\">";
CocoBlockly.toolboxStr += "                     <block type=\"io_digitalwrite\" id=\"dH-pBT`M6@_IS\/d?X3|e\">";
CocoBlockly.toolboxStr += "                        <field name=\"PIN\">PB4<\/field>";
CocoBlockly.toolboxStr += "                        <value name=\"STATE\">";
CocoBlockly.toolboxStr += "                           <block type=\"variables_get\" id=\"q.QhVw^ad%\/Kn\/#YwKN_\">";
CocoBlockly.toolboxStr += "                              <field name=\"VAR\">toggle_led<\/field>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/value>";
CocoBlockly.toolboxStr += "                        <next>";
CocoBlockly.toolboxStr += "                           <block type=\"variables_set\" id=\"]\/]lgm@@vkz}nFEtq|lm\">";
CocoBlockly.toolboxStr += "                              <field name=\"VAR\">toggle_led<\/field>";
CocoBlockly.toolboxStr += "                              <value name=\"VALUE\">";
CocoBlockly.toolboxStr += "                                 <block type=\"logic_negate\" id=\"d|.]5P?^m73aRm8sYLZD\">";
CocoBlockly.toolboxStr += "                                    <value name=\"BOOL\">";
CocoBlockly.toolboxStr += "                                       <block type=\"variables_get\" id=\"P4Du@TFbd-b,n)dgM=jd\">";
CocoBlockly.toolboxStr += "                                          <field name=\"VAR\">toggle_led<\/field>";
CocoBlockly.toolboxStr += "                                       <\/block>";
CocoBlockly.toolboxStr += "                                    <\/value>";
CocoBlockly.toolboxStr += "                                 <\/block>";
CocoBlockly.toolboxStr += "                              <\/value>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/next>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/statement>";
CocoBlockly.toolboxStr += "               <\/block>";
CocoBlockly.toolboxStr += "            <\/statement>";
CocoBlockly.toolboxStr += "         <\/block>";
CocoBlockly.toolboxStr += "      <\/category>";
CocoBlockly.toolboxStr += "      <category id=\"catCocoTouch\" name=\"CocoTouch to Led\">";
CocoBlockly.toolboxStr += "         <block type=\"arduino_functions\" id=\"rPo^`(@DV6rSUp%#6eYs\" x=\"38\" y=\"38\">";
CocoBlockly.toolboxStr += "            <statement name=\"LOOP_FUNC\">";
CocoBlockly.toolboxStr += "               <block type=\"cocotouch_touched\" id=\"g}~M-6KLuJB`,W9qt?KQ\">";
CocoBlockly.toolboxStr += "                  <statement name=\"COCOTOUCH_DOTOUCHED\">";
CocoBlockly.toolboxStr += "                     <block type=\"cocoutil_peakdetect\" id=\"rp|H2=5u6vB,#sVGr40G\">";
CocoBlockly.toolboxStr += "                        <field name=\"COCO_NAME\">peak_detector_1<\/field>";
CocoBlockly.toolboxStr += "                        <value name=\"COCO_VALUE\">";
CocoBlockly.toolboxStr += "                           <block type=\"variables_get\" id=\"TWSfFo`[i7u:-Q~M%{7v\">";
CocoBlockly.toolboxStr += "                              <field name=\"VAR\">velocityValue<\/field>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/value>";
CocoBlockly.toolboxStr += "                        <statement name=\"COCO_DO\">";
CocoBlockly.toolboxStr += "                           <block type=\"controls_if\" id=\"bHGSMJYcj{1t,T5yMwcs\">";
CocoBlockly.toolboxStr += "                              <mutation else=\"1\" \/>";
CocoBlockly.toolboxStr += "                              <value name=\"IF0\">";
CocoBlockly.toolboxStr += "                                 <block type=\"logic_compare\" id=\"X0L9Kfzm_!#a8^bWXyB@\">";
CocoBlockly.toolboxStr += "                                    <field name=\"OP\">GT<\/field>";
CocoBlockly.toolboxStr += "                                    <value name=\"A\">";
CocoBlockly.toolboxStr += "                                       <block type=\"variables_get\" id=\"t!`@Bc;(NsP)]2Lb^ATI\">";
CocoBlockly.toolboxStr += "                                          <field name=\"VAR\">prevVelocity<\/field>";
CocoBlockly.toolboxStr += "                                       <\/block>";
CocoBlockly.toolboxStr += "                                    <\/value>";
CocoBlockly.toolboxStr += "                                    <value name=\"B\">";
CocoBlockly.toolboxStr += "                                       <block type=\"math_number\" id=\"NKGWYlE*^NoWWI5C01fH\">";
CocoBlockly.toolboxStr += "                                          <field name=\"NUM\">520<\/field>";
CocoBlockly.toolboxStr += "                                       <\/block>";
CocoBlockly.toolboxStr += "                                    <\/value>";
CocoBlockly.toolboxStr += "                                 <\/block>";
CocoBlockly.toolboxStr += "                              <\/value>";
CocoBlockly.toolboxStr += "                              <statement name=\"DO0\">";
CocoBlockly.toolboxStr += "                                 <block type=\"io_digitalwrite\" id=\"CHTen!b1?|No3lvZvsG]\">";
CocoBlockly.toolboxStr += "                                    <field name=\"PIN\">PB1<\/field>";
CocoBlockly.toolboxStr += "                                    <value name=\"STATE\">";
CocoBlockly.toolboxStr += "                                       <block type=\"io_highlow\" id=\"rIWPXr0]a(Xd`u,Kpctz\">";
CocoBlockly.toolboxStr += "                                          <field name=\"STATE\">HIGH<\/field>";
CocoBlockly.toolboxStr += "                                       <\/block>";
CocoBlockly.toolboxStr += "                                    <\/value>";
CocoBlockly.toolboxStr += "                                    <next>";
CocoBlockly.toolboxStr += "                                       <block type=\"cocomidi_sendcchires\" id=\"u:sr*?6Q_3_;_%kKsV`7\" disabled=\"true\">";
CocoBlockly.toolboxStr += "                                          <value name=\"COCOMIDI_VALUE\">";
CocoBlockly.toolboxStr += "                                             <block type=\"variables_get\" id=\"bnnbbf^4cgHVV9JT#j+5\">";
CocoBlockly.toolboxStr += "                                                <field name=\"VAR\">prevVelocity<\/field>";
CocoBlockly.toolboxStr += "                                             <\/block>";
CocoBlockly.toolboxStr += "                                          <\/value>";
CocoBlockly.toolboxStr += "                                          <value name=\"COCOMIDI_CHAN\">";
CocoBlockly.toolboxStr += "                                             <block type=\"math_number\" id=\"xCxn@SzM+C!SA~VV,XVw\">";
CocoBlockly.toolboxStr += "                                                <field name=\"NUM\">1<\/field>";
CocoBlockly.toolboxStr += "                                             <\/block>";
CocoBlockly.toolboxStr += "                                          <\/value>";
CocoBlockly.toolboxStr += "                                       <\/block>";
CocoBlockly.toolboxStr += "                                    <\/next>";
CocoBlockly.toolboxStr += "                                 <\/block>";
CocoBlockly.toolboxStr += "                              <\/statement>";
CocoBlockly.toolboxStr += "                              <statement name=\"ELSE\">";
CocoBlockly.toolboxStr += "                                 <block type=\"cocomidi_sendcchires\" id=\",NK5e8npiD!{]Hh.Gy|,\" disabled=\"true\">";
CocoBlockly.toolboxStr += "                                    <value name=\"COCOMIDI_VALUE\">";
CocoBlockly.toolboxStr += "                                       <block type=\"math_number\" id=\"y8a5_g{C~bc##WK!.)j1\">";
CocoBlockly.toolboxStr += "                                          <field name=\"NUM\">0<\/field>";
CocoBlockly.toolboxStr += "                                       <\/block>";
CocoBlockly.toolboxStr += "                                    <\/value>";
CocoBlockly.toolboxStr += "                                    <value name=\"COCOMIDI_CHAN\">";
CocoBlockly.toolboxStr += "                                       <block type=\"math_number\" id=\"5\/o\/\/)a^KW=SwIVGxhJ1\">";
CocoBlockly.toolboxStr += "                                          <field name=\"NUM\">1<\/field>";
CocoBlockly.toolboxStr += "                                       <\/block>";
CocoBlockly.toolboxStr += "                                    <\/value>";
CocoBlockly.toolboxStr += "                                 <\/block>";
CocoBlockly.toolboxStr += "                              <\/statement>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/statement>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/statement>";
CocoBlockly.toolboxStr += "                  <next>";
CocoBlockly.toolboxStr += "                     <block type=\"coco_interval_function\" id=\"RU)C%,4]UWYoZ.I5WQ0_\">";
CocoBlockly.toolboxStr += "                        <field name=\"TIMER_NAME\">default<\/field>";
CocoBlockly.toolboxStr += "                        <value name=\"TIMER_INTERVAL\">";
CocoBlockly.toolboxStr += "                           <block type=\"math_number\" id=\"Ao]7q9mW~,@7TI3^[y5r\">";
CocoBlockly.toolboxStr += "                              <field name=\"NUM\">1000<\/field>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/value>";
CocoBlockly.toolboxStr += "                        <statement name=\"DO_BLOCKS\">";
CocoBlockly.toolboxStr += "                           <block type=\"io_digitalwrite\" id=\"l5`wt~Vp?t.0]cMnxCTS\">";
CocoBlockly.toolboxStr += "                              <field name=\"PIN\">PB1<\/field>";
CocoBlockly.toolboxStr += "                              <value name=\"STATE\">";
CocoBlockly.toolboxStr += "                                 <block type=\"io_highlow\" id=\"e|Rk6-(b6f2_tz`q:l^?\">";
CocoBlockly.toolboxStr += "                                    <field name=\"STATE\">LOW<\/field>";
CocoBlockly.toolboxStr += "                                 <\/block>";
CocoBlockly.toolboxStr += "                              <\/value>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/statement>";
CocoBlockly.toolboxStr += "                        <next>";
CocoBlockly.toolboxStr += "                           <block type=\"cocomidi_update\" id=\":w?.oZcQNUU3+Q%C%f=^\" disabled=\"true\" \/>";
CocoBlockly.toolboxStr += "                        <\/next>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/next>";
CocoBlockly.toolboxStr += "               <\/block>";
CocoBlockly.toolboxStr += "            <\/statement>";
CocoBlockly.toolboxStr += "         <\/block>";
CocoBlockly.toolboxStr += "      <\/category>";
CocoBlockly.toolboxStr += "      <category id=\"catCocoTouch\" name=\"CocoTouch to Midi\">";
CocoBlockly.toolboxStr += "         <block type=\"arduino_functions\" id=\"jt2UYe\/a:4opih^:VQ`^\" x=\"37\" y=\"38\">";
CocoBlockly.toolboxStr += "            <statement name=\"LOOP_FUNC\">";
CocoBlockly.toolboxStr += "               <block type=\"cocotouch_touched\" id=\"le|kxys6yaW20{S|+eXd\">";
CocoBlockly.toolboxStr += "                  <statement name=\"COCOTOUCH_DOTOUCHED\">";
CocoBlockly.toolboxStr += "                     <block type=\"cocomidi_sendcchires\" id=\"g_(mUH|XSPN*et\/tmi_M\">";
CocoBlockly.toolboxStr += "                        <value name=\"COCOMIDI_VALUE\">";
CocoBlockly.toolboxStr += "                           <block type=\"variables_get\" id=\"]y8:aJT_sqB}[0.oBL7.\">";
CocoBlockly.toolboxStr += "                              <field name=\"VAR\">filtered_value<\/field>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/value>";
CocoBlockly.toolboxStr += "                        <value name=\"COCOMIDI_CHAN\">";
CocoBlockly.toolboxStr += "                           <block type=\"math_number\" id=\"g(|%*{Au|EA*BcTk[w8S\">";
CocoBlockly.toolboxStr += "                              <field name=\"NUM\">1<\/field>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/value>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/statement>";
CocoBlockly.toolboxStr += "                  <next>";
CocoBlockly.toolboxStr += "                     <block type=\"cocomidi_update\" id=\"6jAg-g-R-821#79iBZX`\" \/>";
CocoBlockly.toolboxStr += "                  <\/next>";
CocoBlockly.toolboxStr += "               <\/block>";
CocoBlockly.toolboxStr += "            <\/statement>";
CocoBlockly.toolboxStr += "         <\/block>";
CocoBlockly.toolboxStr += "      <\/category>";
CocoBlockly.toolboxStr += "      <category id=\"catCocoMidi\" name=\"CocoMidi\">";
CocoBlockly.toolboxStr += "         <block type=\"arduino_functions\" id=\"Gfs=i-2ol,.H[PFJytg(\" x=\"63\" y=\"88\">";
CocoBlockly.toolboxStr += "            <statement name=\"LOOP_FUNC\">";
CocoBlockly.toolboxStr += "               <block type=\"cocomidi_sendnote_var\" id=\"SZV=[c-09L;lgu-cC[80\">";
CocoBlockly.toolboxStr += "                  <value name=\"COCOMIDI_STATE\">";
CocoBlockly.toolboxStr += "                     <block type=\"cocomidi_note_state\" id=\"6t}AyCckvHfyBJMQ[ps]\">";
CocoBlockly.toolboxStr += "                        <field name=\"MIDI_NOTE_STATE\">MIDI_NOTEON<\/field>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/value>";
CocoBlockly.toolboxStr += "                  <value name=\"COCOMIDI_CHAN\">";
CocoBlockly.toolboxStr += "                     <block type=\"math_number\" id=\"(lY+A#b}:9?v@oBmied%\">";
CocoBlockly.toolboxStr += "                        <field name=\"NUM\">22<\/field>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/value>";
CocoBlockly.toolboxStr += "                  <value name=\"COCOMIDI_VEL\">";
CocoBlockly.toolboxStr += "                     <block type=\"math_number\" id=\"m2?u-m:pR+U*[DwmjnWj\">";
CocoBlockly.toolboxStr += "                        <field name=\"NUM\">127<\/field>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/value>";
CocoBlockly.toolboxStr += "                  <next>";
CocoBlockly.toolboxStr += "                     <block type=\"cocomidi_delay\" id=\"RQ[U*2U`nuOtn%pam3YI\">";
CocoBlockly.toolboxStr += "                        <value name=\"COCOMIDI_DELAY\">";
CocoBlockly.toolboxStr += "                           <block type=\"math_number\" id=\"eSzr;WN5_[7@r0NC:KX=\">";
CocoBlockly.toolboxStr += "                              <field name=\"NUM\">500<\/field>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/value>";
CocoBlockly.toolboxStr += "                        <next>";
CocoBlockly.toolboxStr += "                           <block type=\"cocomidi_sendnote_var\" id=\"UvQ0RrSBXTYq@_\/^jy7w\">";
CocoBlockly.toolboxStr += "                              <value name=\"COCOMIDI_STATE\">";
CocoBlockly.toolboxStr += "                                 <block type=\"cocomidi_note_state\" id=\"w|pPWlU2{F*#yk36=]HU\">";
CocoBlockly.toolboxStr += "                                    <field name=\"MIDI_NOTE_STATE\">MIDI_NOTEON<\/field>";
CocoBlockly.toolboxStr += "                                 <\/block>";
CocoBlockly.toolboxStr += "                              <\/value>";
CocoBlockly.toolboxStr += "                              <value name=\"COCOMIDI_CHAN\">";
CocoBlockly.toolboxStr += "                                 <block type=\"math_number\" id=\"]U=BoPM|4M@H0xRru9=l\">";
CocoBlockly.toolboxStr += "                                    <field name=\"NUM\">22<\/field>";
CocoBlockly.toolboxStr += "                                 <\/block>";
CocoBlockly.toolboxStr += "                              <\/value>";
CocoBlockly.toolboxStr += "                              <value name=\"COCOMIDI_VEL\">";
CocoBlockly.toolboxStr += "                                 <block type=\"math_number\" id=\"4XPw~(I-5AX_[gAP[RDl\">";
CocoBlockly.toolboxStr += "                                    <field name=\"NUM\">127<\/field>";
CocoBlockly.toolboxStr += "                                 <\/block>";
CocoBlockly.toolboxStr += "                              <\/value>";
CocoBlockly.toolboxStr += "                              <next>";
CocoBlockly.toolboxStr += "                                 <block type=\"cocomidi_delay\" id=\"6Gy8(ln!)232WCTbtczw\">";
CocoBlockly.toolboxStr += "                                    <value name=\"COCOMIDI_DELAY\">";
CocoBlockly.toolboxStr += "                                       <block type=\"math_number\" id=\"9QQMKwX.es;R|a1KkB8C\">";
CocoBlockly.toolboxStr += "                                          <field name=\"NUM\">500<\/field>";
CocoBlockly.toolboxStr += "                                       <\/block>";
CocoBlockly.toolboxStr += "                                    <\/value>";
CocoBlockly.toolboxStr += "                                 <\/block>";
CocoBlockly.toolboxStr += "                              <\/next>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/next>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/next>";
CocoBlockly.toolboxStr += "               <\/block>";
CocoBlockly.toolboxStr += "            <\/statement>";
CocoBlockly.toolboxStr += "         <\/block>";
CocoBlockly.toolboxStr += "      <\/category>";
CocoBlockly.toolboxStr += "      <category id=\"catCocoMidi\" name=\"Potentio to CocoMidi\">";
CocoBlockly.toolboxStr += "         <block type=\"arduino_functions\" id=\"5Z;sl%)oCHl3Cn=6q%,,\" x=\"9\" y=\"3\">";
CocoBlockly.toolboxStr += "            <statement name=\"LOOP_FUNC\">";
CocoBlockly.toolboxStr += "               <block type=\"cocomidi_sendcchires\" id=\"I6,Pt_hsL)D@Zu46p_^[\">";
CocoBlockly.toolboxStr += "                  <value name=\"COCOMIDI_VALUE\">";
CocoBlockly.toolboxStr += "                     <block type=\"io_analogread\" id=\"[a7Rtx\/3pW)ceu%?7lK~\">";
CocoBlockly.toolboxStr += "                        <field name=\"PIN\">A1<\/field>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/value>";
CocoBlockly.toolboxStr += "                  <value name=\"COCOMIDI_CHAN\">";
CocoBlockly.toolboxStr += "                     <block type=\"math_number\" id=\"7xxz3iUe8;BDZvI\/5H]2\">";
CocoBlockly.toolboxStr += "                        <field name=\"NUM\">1<\/field>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/value>";
CocoBlockly.toolboxStr += "                  <next>";
CocoBlockly.toolboxStr += "                     <block type=\"cocomidi_delay\" id=\"O8M`2V:a5-L81PVvhW@\/\">";
CocoBlockly.toolboxStr += "                        <value name=\"COCOMIDI_DELAY\">";
CocoBlockly.toolboxStr += "                           <block type=\"math_number\" id=\"pK9nwuf\/Sz_8YQ3FlP*p\">";
CocoBlockly.toolboxStr += "                              <field name=\"NUM\">5<\/field>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/value>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/next>";
CocoBlockly.toolboxStr += "               <\/block>";
CocoBlockly.toolboxStr += "            <\/statement>";
CocoBlockly.toolboxStr += "         <\/block>";
CocoBlockly.toolboxStr += "      <\/category>";
CocoBlockly.toolboxStr += "      <category id=\"catCocoSynth\" name=\"CocoSynth\">";
CocoBlockly.toolboxStr += "         <block type=\"arduino_functions\" id=\"^}@SOl,N#YB49.qgQN]M\" x=\"38\" y=\"38\">";
CocoBlockly.toolboxStr += "            <statement name=\"SETUP_FUNC\">";
CocoBlockly.toolboxStr += "               <block type=\"coco_synth_setupvoice\" id=\"jP,[^(j_i6y1\/vP,x1|8\" inline=\"false\">";
CocoBlockly.toolboxStr += "                  <field name=\"COCO_VOICE\">0<\/field>";
CocoBlockly.toolboxStr += "                  <field name=\"COCO_WAVEFORM\">SINE<\/field>";
CocoBlockly.toolboxStr += "                  <field name=\"COCO_ENVELOPE\">ENVELOPE0<\/field>";
CocoBlockly.toolboxStr += "                  <field name=\"COCO_PITCH\">77<\/field>";
CocoBlockly.toolboxStr += "                  <field name=\"COCO_LENGTH\">60<\/field>";
CocoBlockly.toolboxStr += "                  <field name=\"COCO_MOD\">64<\/field>";
CocoBlockly.toolboxStr += "                  <comment pinned=\"true\" h=\"80\" w=\"160\">Connect your speaker to pin 5";
CocoBlockly.toolboxStr += "Sine wave instrument<\/comment>";
CocoBlockly.toolboxStr += "                  <next>";
CocoBlockly.toolboxStr += "                     <block type=\"coco_synth_setupvoice\" id=\"^pTol#6@O}6=7MR%rEk`\" inline=\"false\" collapsed=\"true\">";
CocoBlockly.toolboxStr += "                        <field name=\"COCO_VOICE\">1<\/field>";
CocoBlockly.toolboxStr += "                        <field name=\"COCO_WAVEFORM\">NOISE<\/field>";
CocoBlockly.toolboxStr += "                        <field name=\"COCO_ENVELOPE\">ENVELOPE0<\/field>";
CocoBlockly.toolboxStr += "                        <field name=\"COCO_PITCH\">50<\/field>";
CocoBlockly.toolboxStr += "                        <field name=\"COCO_LENGTH\">100<\/field>";
CocoBlockly.toolboxStr += "                        <field name=\"COCO_MOD\">32<\/field>";
CocoBlockly.toolboxStr += "                        <comment pinned=\"false\" h=\"80\" w=\"160\">Noise Instrument setup<\/comment>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/next>";
CocoBlockly.toolboxStr += "               <\/block>";
CocoBlockly.toolboxStr += "            <\/statement>";
CocoBlockly.toolboxStr += "            <statement name=\"LOOP_FUNC\">";
CocoBlockly.toolboxStr += "               <block type=\"cocosynth_interval_function\" id=\"~B8r^bj{E;NjR;M~,}8[\">";
CocoBlockly.toolboxStr += "                  <field name=\"TIMER_NAME\">synth_timer_1<\/field>";
CocoBlockly.toolboxStr += "                  <comment pinned=\"true\" h=\"80\" w=\"160\">every 1 sec trigger metronome<\/comment>";
CocoBlockly.toolboxStr += "                  <value name=\"TIMER_INTERVAL\">";
CocoBlockly.toolboxStr += "                     <block type=\"math_number\" id=\"!!xw1WI#qCYFd*DDt,v9\">";
CocoBlockly.toolboxStr += "                        <field name=\"NUM\">1000<\/field>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/value>";
CocoBlockly.toolboxStr += "                  <statement name=\"DO_BLOCKS\">";
CocoBlockly.toolboxStr += "                     <block type=\"coco_synth_trigger\" id=\"k#**O~xu3VaEGMV6q8vc\">";
CocoBlockly.toolboxStr += "                        <value name=\"NAME\">";
CocoBlockly.toolboxStr += "                           <block type=\"math_number\" id=\"TM=3w+Rs:.2tTeaIrH!q\">";
CocoBlockly.toolboxStr += "                              <field name=\"NUM\">0<\/field>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/value>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/statement>";
CocoBlockly.toolboxStr += "                  <next>";
CocoBlockly.toolboxStr += "                     <block type=\"cocosynth_interval_function\" id=\"wce5](b4h6H:U4}MwHwL\">";
CocoBlockly.toolboxStr += "                        <field name=\"TIMER_NAME\">synth_timer_2<\/field>";
CocoBlockly.toolboxStr += "                        <comment pinned=\"false\" h=\"80\" w=\"160\">every 2 sec trigger noise instrument<\/comment>";
CocoBlockly.toolboxStr += "                        <value name=\"TIMER_INTERVAL\">";
CocoBlockly.toolboxStr += "                           <block type=\"math_number\" id=\"yA;mqzu%REf[`Dna]wR,\">";
CocoBlockly.toolboxStr += "                              <field name=\"NUM\">2000<\/field>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/value>";
CocoBlockly.toolboxStr += "                        <statement name=\"DO_BLOCKS\">";
CocoBlockly.toolboxStr += "                           <block type=\"coco_synth_miditrigger\" id=\"M`VMwwM4u?-[UOvcm:W[\">";
CocoBlockly.toolboxStr += "                              <value name=\"NAME\">";
CocoBlockly.toolboxStr += "                                 <block type=\"math_number\" id=\"I~kA!gArS8.44rAa=A!G\">";
CocoBlockly.toolboxStr += "                                    <field name=\"NUM\">1<\/field>";
CocoBlockly.toolboxStr += "                                 <\/block>";
CocoBlockly.toolboxStr += "                              <\/value>";
CocoBlockly.toolboxStr += "                              <value name=\"NOTE\">";
CocoBlockly.toolboxStr += "                                 <block type=\"math_random_int\" id=\"U46gXu#9Iome+Y(VM,Ct\">";
CocoBlockly.toolboxStr += "                                    <value name=\"FROM\">";
CocoBlockly.toolboxStr += "                                       <block type=\"math_number\" id=\"_QV*zM@aq-0U}u14)gdX\">";
CocoBlockly.toolboxStr += "                                          <field name=\"NUM\">1<\/field>";
CocoBlockly.toolboxStr += "                                       <\/block>";
CocoBlockly.toolboxStr += "                                    <\/value>";
CocoBlockly.toolboxStr += "                                    <value name=\"TO\">";
CocoBlockly.toolboxStr += "                                       <block type=\"math_number\" id=\"j8AdqP7W~_d.2{:o%;x2\">";
CocoBlockly.toolboxStr += "                                          <field name=\"NUM\">100<\/field>";
CocoBlockly.toolboxStr += "                                       <\/block>";
CocoBlockly.toolboxStr += "                                    <\/value>";
CocoBlockly.toolboxStr += "                                 <\/block>";
CocoBlockly.toolboxStr += "                              <\/value>";
CocoBlockly.toolboxStr += "                           <\/block>";
CocoBlockly.toolboxStr += "                        <\/statement>";
CocoBlockly.toolboxStr += "                     <\/block>";
CocoBlockly.toolboxStr += "                  <\/next>";
CocoBlockly.toolboxStr += "               <\/block>";
CocoBlockly.toolboxStr += "            <\/statement>";
CocoBlockly.toolboxStr += "         <\/block>";
CocoBlockly.toolboxStr += "      <\/category>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catLogic\" name=\"Logic\">";
CocoBlockly.toolboxStr += "      <block type=\"controls_if\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"logic_compare\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"logic_operation\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"logic_negate\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"logic_boolean\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"logic_null\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"logic_ternary\" \/>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catLoops\" name=\"Loops\">";
CocoBlockly.toolboxStr += "      <block type=\"controls_repeat_ext\">";
CocoBlockly.toolboxStr += "         <value name=\"TIMES\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">10<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"controls_whileUntil\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"controls_for\">";
CocoBlockly.toolboxStr += "         <value name=\"FROM\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">1<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "         <value name=\"TO\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">10<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "         <value name=\"BY\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">1<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"controls_flow_statements\" \/>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catMath\" name=\"Math\">";
CocoBlockly.toolboxStr += "      <block type=\"math_number\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"math_arithmetic\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"math_single\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"math_trig\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"math_constant\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"math_number_property\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"math_change\">";
CocoBlockly.toolboxStr += "         <value name=\"DELTA\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">1<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"math_round\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"math_modulo\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"math_constrain\">";
CocoBlockly.toolboxStr += "         <value name=\"LOW\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">1<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "         <value name=\"HIGH\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">100<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"math_random_int\">";
CocoBlockly.toolboxStr += "         <value name=\"FROM\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">1<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "         <value name=\"TO\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">100<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"math_random_float\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"base_map\" \/>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catText\" name=\"Text\">";
CocoBlockly.toolboxStr += "      <block type=\"text\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"cocomake_singlechar\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"text_join\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"text_append\">";
CocoBlockly.toolboxStr += "         <value name=\"TEXT\">";
CocoBlockly.toolboxStr += "            <block type=\"text\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"text_length\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"text_isEmpty\" \/>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catVariables\" name=\"Variables\">";
CocoBlockly.toolboxStr += "      <block type=\"variables_get\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"variables_set\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"variables_set\">";
CocoBlockly.toolboxStr += "         <value name=\"VALUE\">";
CocoBlockly.toolboxStr += "            <block type=\"variables_set_type\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"variables_set_type\" \/>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catFunctions\" name=\"Functions\" custom=\"PROCEDURE\" \/>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catInputOutput\" name=\"Input\/Output\">";
CocoBlockly.toolboxStr += "      <block type=\"variables_set\">";
CocoBlockly.toolboxStr += "         <value name=\"VALUE\">";
CocoBlockly.toolboxStr += "            <block type=\"io_analogread\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"variables_set\">";
CocoBlockly.toolboxStr += "         <value name=\"VALUE\">";
CocoBlockly.toolboxStr += "            <block type=\"io_digitalread\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"io_digitalwrite\">";
CocoBlockly.toolboxStr += "         <value name=\"STATE\">";
CocoBlockly.toolboxStr += "            <block type=\"io_highlow\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"io_digitalread\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"coco_readpullup\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"io_builtin_led\">";
CocoBlockly.toolboxStr += "         <value name=\"STATE\">";
CocoBlockly.toolboxStr += "            <block type=\"io_highlow\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"io_analogwrite\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"io_analogread\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"io_highlow\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"io_pulsein\">";
CocoBlockly.toolboxStr += "         <value name=\"PULSETYPE\">";
CocoBlockly.toolboxStr += "            <shadow type=\"io_highlow\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"io_pulsetimeout\">";
CocoBlockly.toolboxStr += "         <value name=\"PULSETYPE\">";
CocoBlockly.toolboxStr += "            <shadow type=\"io_highlow\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "         <value name=\"TIMEOUT\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catTime\" name=\"Time\">";
CocoBlockly.toolboxStr += "      <block type=\"time_delay\">";
CocoBlockly.toolboxStr += "         <value name=\"DELAY_TIME_MILI\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">1000<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"coco_interval_function\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"time_delaymicros\">";
CocoBlockly.toolboxStr += "         <value name=\"DELAY_TIME_MICRO\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">100<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"time_millis\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"time_micros\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"coco_delayms\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"coco_delayus\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"coco_delayms\" id=\"n8!w)48dfFK;8MobuzE:\" x=\"112\" y=\"362\">";
CocoBlockly.toolboxStr += "         <value name=\"COCOMIDI_DELAY\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\" id=\"8Xx.],i5o:Iaqx+tc@!W\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">100<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"infinite_loop\" \/>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catAudio\" name=\"Audio\">";
CocoBlockly.toolboxStr += "      <block type=\"io_tone\">";
CocoBlockly.toolboxStr += "         <field name=\"TONEPIN\">0<\/field>";
CocoBlockly.toolboxStr += "         <value name=\"FREQUENCY\">";
CocoBlockly.toolboxStr += "            <shadow type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">220<\/field>";
CocoBlockly.toolboxStr += "            <\/shadow>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"io_notone\" \/>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catMotors\" name=\"Motors\">";
CocoBlockly.toolboxStr += "      <block type=\"servo_write\">";
CocoBlockly.toolboxStr += "         <value name=\"SERVO_ANGLE\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">90<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"servo_read\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"stepper_config\">";
CocoBlockly.toolboxStr += "         <field name=\"STEPPER_PIN1\">1<\/field>";
CocoBlockly.toolboxStr += "         <field name=\"STEPPER_PIN2\">2<\/field>";
CocoBlockly.toolboxStr += "         <value name=\"STEPPER_STEPS\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">100<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "         <value name=\"STEPPER_SPEED\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">10<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"stepper_step\">";
CocoBlockly.toolboxStr += "         <value name=\"STEPPER_STEPS\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">10<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catComms\" name=\"Comms\">";
CocoBlockly.toolboxStr += "      <block type=\"serial_setup\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"serial_print\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"text_prompt_ext\">";
CocoBlockly.toolboxStr += "         <value name=\"TEXT\">";
CocoBlockly.toolboxStr += "            <block type=\"text\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"spi_setup\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"spi_transfer\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"spi_transfer_return\" \/>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catCocoKey\" name=\"CocoKeyboard\">";
CocoBlockly.toolboxStr += "      <block type=\"cocokey_sendkeystroke\">";
CocoBlockly.toolboxStr += "         <value name=\"COCOKEY_STROKE\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">0<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"cocokey_sendkeystroke\">";
CocoBlockly.toolboxStr += "         <value name=\"COCOKEY_STROKE\">";
CocoBlockly.toolboxStr += "            <block type=\"cocomake_singlechar\">";
CocoBlockly.toolboxStr += "               <field name=\"TEXT\">C<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"cocokey_delay\">";
CocoBlockly.toolboxStr += "         <value name=\"COCOKEY_DELAY\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">500<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"cocokey_print\">";
CocoBlockly.toolboxStr += "         <value name=\"COCOKEY_PRINT\">";
CocoBlockly.toolboxStr += "            <block type=\"text\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"cocokey_update\" \/>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catCocoMidi\" name=\"CocoMidi\">";
CocoBlockly.toolboxStr += "      <block type=\"cocomidi_sendnote_var\">";
CocoBlockly.toolboxStr += "         <value name=\"COCOMIDI_STATE\">";
CocoBlockly.toolboxStr += "            <block type=\"cocomidi_note_state\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "         <value name=\"COCOMIDI_CHAN\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">0<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "         <value name=\"COCOMIDI_VEL\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">0<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"cocomidi_sendcchires\">";
CocoBlockly.toolboxStr += "         <value name=\"COCOMIDI_VALUE\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">0<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "         <value name=\"COCOMIDI_CHAN\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">1<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"cocomidi_sendcchires\">";
CocoBlockly.toolboxStr += "         <value name=\"COCOMIDI_VALUE\">";
CocoBlockly.toolboxStr += "            <block type=\"variables_get\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "         <value name=\"COCOMIDI_CHAN\">";
CocoBlockly.toolboxStr += "            <block type=\"variables_get\" \/>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"cocomidi_update\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"cocomidi_note_state\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"cocomidi_message\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"cocomidi_read\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"cocomidi_delay\">";
CocoBlockly.toolboxStr += "         <value name=\"COCOMIDI_DELAY\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">500<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catCocoMouse\" name=\"CocoMouse\">";
CocoBlockly.toolboxStr += "      <block type=\"cocokey_update\" \/>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catCocoTouch\" name=\"CocoTouch\">";
CocoBlockly.toolboxStr += "      <block type=\"cocotouch_touched\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"variables_get\">";
CocoBlockly.toolboxStr += "         <field name=\"VAR\">velocityValue<\/field>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"variables_get\">";
CocoBlockly.toolboxStr += "         <field name=\"VAR\">prevVelocity<\/field>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"variables_get\">";
CocoBlockly.toolboxStr += "         <field name=\"VAR\">filtered_value<\/field>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catCocoSynth\" name=\"CocoSynth\">";
CocoBlockly.toolboxStr += "      <block type=\"coco_synth_setupvoice\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"coco_synth_delay\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"cocosynth_interval_function\" id=\"l#cYCg3[Xafg#bmHLYz6\" x=\"162\" y=\"488\">";
CocoBlockly.toolboxStr += "         <field name=\"TIMER_NAME\">synth_timer_1<\/field>";
CocoBlockly.toolboxStr += "         <value name=\"TIMER_INTERVAL\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\" id=\";=T})9b-GmWh.s+xKPpt\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">1000<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "      <block type=\"coco_synth_setmod\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"coco_synth_setmod_field\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"coco_synth_trigger\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"coco_synth_miditrigger\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"coco_synth_voice\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"coco_synth_setwave_field\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"coco_synth_setenvelope_field\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"coco_synth_setpitch\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"coco_synth_setlength\" \/>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "   <sep \/>";
CocoBlockly.toolboxStr += "   <category id=\"catCocoUtil\" name=\"CocoUtil\">";
CocoBlockly.toolboxStr += "      <block type=\"cocoutil_peakdetect\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"cocoutil_getvelocity\" \/>";
CocoBlockly.toolboxStr += "      <block type=\"cocoutil_getmova\" id=\"2aiF`je~9wv+%8u+HhEh\" x=\"163\" y=\"188\">";
CocoBlockly.toolboxStr += "         <field name=\"COCO_NAME\">coco_mova_1<\/field>";
CocoBlockly.toolboxStr += "         <value name=\"COCO_MA\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\" id=\"tR6T(Mzr*EsVe\/*(f_uM\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">0.2<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "         <value name=\"COCO_VALUE\">";
CocoBlockly.toolboxStr += "            <block type=\"math_number\" id=\"Xmi6=.7+8I(y_|V3*pIS\">";
CocoBlockly.toolboxStr += "               <field name=\"NUM\">0<\/field>";
CocoBlockly.toolboxStr += "            <\/block>";
CocoBlockly.toolboxStr += "         <\/value>";
CocoBlockly.toolboxStr += "      <\/block>";
CocoBlockly.toolboxStr += "   <\/category>";
CocoBlockly.toolboxStr += "<\/xml>";
